sudo apt-get install -y python3.8
sudo apt-get install -y python-pip
sudo apt-get install -y python-Babel==2.9.0
sudo apt-get install -y python-click==7.1.2
sudo apt-get install -y python-Flask==1.1.2
sudo apt-get install -y python-Flask-API==2.0
sudo apt-get install -y python-Flask-Babel==2.0.0
sudo apt-get install -y python-Flask-SQLAlchemy==2.4.4
sudo apt-get install -y python-Flask-Table==0.5.0
sudo apt-get install -y python-gunicorn==20.0.4
sudo apt-get install -y python-itsdangerous==1.1.0
sudo apt-get install -y python-pytz==2021.1
sudo apt-get install -y python-SQLAlchemy==1.3.23
sudo apt-get install -y python-Werkzeug==1.0.1
sudo apt-get install -y python-requests==2.25.1